### ISSUE TITLE
view example

### ISSUE THREAD

**Issue by untrabeer** [adessoAG/kong-plugin-soap2rest#2]
Could you show some example for config service,route and config plugin thank in advance

**Comment by DanielKraft** [comment]
As already described in the README, see [Enabling Plugin](https://github.com/adessoAG/kong-plugin-soap2rest#enabling-plugin), the plugin needs the following configuration (here exemplary for [`service`](https://github.com/adessoAG/kong-plugin-soap2rest#service)):

<details open="open">
    <summary><b>Kong Admin API</b></summary>

```bash
curl -X POST http://localhost:8001/services/{service}/plugins \
    --data "name=soap2rest" \
    --data "config.rest_base_path=<rest base path>" \
    --data "config.openapi_yaml_path=<openapi yaml path>" \
    --data "config.wsdl_path=<wsdl path>" \
    --data "config.operation_mapping.<operation id>=<operation path>"
```

</details>

<details open="open">
    <summary><b>Declarative (YAML)</b></summary>

```yml
plugins:
- name: soap2rest
  service: <service>
  config:
    rest_base_path: <rest base path>
    openapi_yaml_path: <openapi yaml path>
    wsdl_path: <wsdl path>
    operation_mapping:
      <operation id>: <operation path>
```

</details>

### `config.rest_base_path`
* This parameter requires the path to the REST API into which the SOAP request should be converted.
* Example: `config.openapi_yaml_path=/rest/api/v1/`

### `config.openapi_yaml_path`
* For this parameter a file must be stored on the Kong system.
* This file must be a valid [OpenAPI](https://oai.github.io/Documentation/introduction.html) specification! 
* Example: `config.openapi_yaml_path=/home/data/openapi.yaml`

### `config.wsdl_path`
* For this parameter a file must be stored on the Kong system.
* This file must be a valid [WSDL](https://www.soapui.org/docs/soap-and-wsdl/working-with-wsdls/) file! 
* Example: `config.openapi_yaml_path=/home/data/soapapi.wsdl`

### `config.operation_mapping` _(optional)_
* This parameter can be used to specify special path translations, such as REST paths with parameters.
* This requires a SOAP OperationsId and the associated REST path.
* Example: `config.operation_mapping.GetPetById=pet/{id}`


> **No further configuration is required, as the plugin reads the OpenAPI and the WSDL and internally performs a mapping of the two interfaces.**
